In [1]:
import torch
import numpy as np

In [2]:
a = torch.tensor([[2, 5, 1], [8, 9, 11]])
a

tensor([[ 2,  5,  1],
        [ 8,  9, 11]])

In [3]:
b = torch.tensor([[3, 8, 2], [7, 4, 6]])
a

tensor([[ 2,  5,  1],
        [ 8,  9, 11]])

In [4]:
a.T

tensor([[ 2,  8],
        [ 5,  9],
        [ 1, 11]])

In [5]:
torch.matmul(a.T, b)

tensor([[62, 48, 52],
        [78, 76, 64],
        [80, 52, 68]])

In [6]:
torch.matmul(b, a.T)

tensor([[ 48, 118],
        [ 40, 158]])

In [7]:
sym_mt = torch.tensor([[1,2,3], [2,4, 4], [3, 4, 6]])
sym_mt

tensor([[1, 2, 3],
        [2, 4, 4],
        [3, 4, 6]])

In [8]:
sym_mt.T

tensor([[1, 2, 3],
        [2, 4, 4],
        [3, 4, 6]])

In [9]:
sym_mt.T == sym_mt

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [10]:
I = np.array([[1,0,0], [0,1,0], [0,0,1]])
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [11]:
first_column = I[:, 0]
first_column

array([1, 0, 0])

In [12]:
second_column = I[:, 1]
second_column

array([0, 1, 0])

In [13]:
third_column = I[:, 2]
third_column

array([0, 0, 1])

In [14]:
summ = 0
for e in first_column:
    e = e * e
    summ += e
np.square(summ)

np.int64(1)

In [15]:
summ = 0
for e in second_column:
    e = e * e
    summ += e
np.square(summ)

np.int64(1)

In [16]:
summ = 0
for e in third_column:
    e = e * e
    summ += e
np.square(summ)

np.int64(1)

In [17]:
np.linalg.norm(first_column), np.linalg.norm(second_column), np.linalg.norm(third_column)

(np.float64(1.0), np.float64(1.0), np.float64(1.0))

In [18]:
K = np.array([[2/3, 1/3, 2/3], [-2/3, 2/3, 1/3], [1/3, 2/3, -2/3]])
K

array([[ 0.66666667,  0.33333333,  0.66666667],
       [-0.66666667,  0.66666667,  0.33333333],
       [ 0.33333333,  0.66666667, -0.66666667]])

In [19]:
for i in range(3):
    col = K[:, i]
    norm = np.linalg.norm(col)
    print(f"Norm of column {i}: {norm}")

Norm of column 0: 0.9999999999999999
Norm of column 1: 0.9999999999999999
Norm of column 2: 0.9999999999999999


In [20]:
# Orthogonal matrix property check

torch.matmul(torch.tensor(K.T, dtype=torch.float32), torch.tensor(K, dtype=torch.float32))

tensor([[1.0000, 0.0000, 0.0000],
        [0.0000, 1.0000, 0.0000],
        [0.0000, 0.0000, 1.0000]])

In [21]:
u1 = np.array([2,5, -3])
u2 = np.array([0, -4, 6])
u1, u2

(array([ 2,  5, -3]), array([ 0, -4,  6]))

In [22]:
matrix_u = np.concatenate((u1.reshape(3,1), u2.reshape(3,1)), axis=1)
matrix_u

array([[ 2,  0],
       [ 5, -4],
       [-3,  6]])

In [23]:
B = np.array([[2, 0, -1], [-2, 3, 1], [0, 4, -1]])

In [24]:
import torch
B = torch.tensor(B, dtype=torch.float32)
B

tensor([[ 2.,  0., -1.],
        [-2.,  3.,  1.],
        [ 0.,  4., -1.]])

In [25]:
u1 = torch.tensor(u1, dtype=torch.float32)
u1

tensor([ 2.,  5., -3.])

In [26]:
B.matmul(u1)

tensor([ 7.,  8., 23.])

In [27]:
X = torch.tensor([[25, 2, 9], [5,26, -5], [3, 7, -14]], dtype=torch.float32)
X

tensor([[ 25.,   2.,   9.],
        [  5.,  26.,  -5.],
        [  3.,   7., -14.]])

In [28]:
eigen_values, eigen_vectors = torch.linalg.eig(X)
eigen_values.dtype, eigen_vectors.dtype

(torch.complex64, torch.complex64)

In [29]:
X = X.to(eigen_values.dtype)

In [30]:
torch.allclose(X.matmul(eigen_vectors), eigen_vectors.matmul(torch.diag(eigen_values)))

True

In [31]:
A = torch.tensor([[-1, 4], [2, -2.]])
A

tensor([[-1.,  4.],
        [ 2., -2.]])

In [32]:
eig_v, eig_vec = torch.linalg.eig(A)
eig_v, eig_vec

(tensor([ 1.3723+0.j, -4.3723+0.j]),
 tensor([[ 0.8601+0.j, -0.7645+0.j],
         [ 0.5101+0.j,  0.6446+0.j]]))

In [33]:
A = A.to(eig_v.dtype)
A

tensor([[-1.+0.j,  4.+0.j],
        [ 2.+0.j, -2.+0.j]])

In [34]:
vec1 = eig_vec[:, 0]
val1 = eig_v[0]
vec1, val1

(tensor([0.8601+0.j, 0.5101+0.j]), tensor(1.3723+0.j))

In [35]:
Av_p = A.matmul(vec1)
Av_p

tensor([1.1803+0.j, 0.7000+0.j])

In [36]:
vec1 * val1

tensor([1.1803+0.j, 0.7000+0.j])

In [37]:
val2 = eig_v[1]
vec2 = eig_vec[:, 1]
val2, vec2

(tensor(-4.3723+0.j), tensor([-0.7645+0.j,  0.6446+0.j]))

In [38]:
Av2_P = A.matmul(vec2)
Av2_P

tensor([ 3.3428+0.j, -2.8182+0.j])

In [39]:
val2 * vec2

tensor([ 3.3428-0.j, -2.8182+0.j])

In [40]:
X = torch.tensor([[25, 2, 9], [5, 26, -5], [3, 7, -14.]])
X

tensor([[ 25.,   2.,   9.],
        [  5.,  26.,  -5.],
        [  3.,   7., -14.]])

In [41]:
eig_val, eig_vec = torch.linalg.eig(X)
eig_val, eig_vec

(tensor([ 29.4214+0.j,  21.2058+0.j, -13.6271+0.j]),
 tensor([[ 0.6633+0.j,  0.6360+0.j, -0.2317+0.j],
         [ 0.7303+0.j, -0.7655+0.j,  0.1505+0.j],
         [ 0.1636+0.j, -0.0980+0.j,  0.9611+0.j]]))

In [42]:
X = X.to(eig_vec.dtype)
X

tensor([[ 25.+0.j,   2.+0.j,   9.+0.j],
        [  5.+0.j,  26.+0.j,  -5.+0.j],
        [  3.+0.j,   7.+0.j, -14.+0.j]])

In [43]:
eig_vec1 = eig_vec[:, 0]
eig_val1 = eig_val[0]
eig_vec1, eig_val1

(tensor([0.6633+0.j, 0.7303+0.j, 0.1636+0.j]), tensor(29.4214+0.j))

In [44]:
X.matmul(eig_vec1)

tensor([19.5144+0.j, 21.4861+0.j,  4.8120+0.j])

In [45]:
eig_val1 * eig_vec1

tensor([19.5144+0.j, 21.4861+0.j,  4.8120+0.j])

In [46]:
torch.allclose(X.matmul(eig_vec1), eig_val1 * eig_vec1)

True

In [47]:
eig_vec2 = eig_vec[:, 1]
eig_val2 = eig_val[1]
eig_vec2, eig_val2

(tensor([ 0.6360+0.j, -0.7655+0.j, -0.0980+0.j]), tensor(21.2058+0.j))

In [48]:
X.matmul(eig_vec2)

tensor([ 13.4861+0.j, -16.2324+0.j,  -2.0783+0.j])

In [49]:
eig_val2 * eig_vec2

tensor([ 13.4861+0.j, -16.2324+0.j,  -2.0783+0.j])

In [50]:
eig_vec3 = eig_vec[:, 2]
eig_val3 = eig_val[2]
eig_vec3, eig_val3

(tensor([-0.2317+0.j,  0.1505+0.j,  0.9611+0.j]), tensor(-13.6271+0.j))

In [51]:
X.matmul(eig_vec3)

tensor([  3.1577+0.j,  -2.0509+0.j, -13.0966+0.j])

In [52]:
eig_val3 * eig_vec3

tensor([  3.1577-0.j,  -2.0509+0.j, -13.0966+0.j])

In [53]:
B_det = torch.tensor([[-2, 0], [0, -2.]])
B_det

tensor([[-2.,  0.],
        [ 0., -2.]])

In [54]:
torch.linalg.det(B_det)

tensor(4.)

In [55]:
C_det = torch.tensor([[2,1,-3], [4,-5,2], [0,-1,3.]])
C_det

tensor([[ 2.,  1., -3.],
        [ 4., -5.,  2.],
        [ 0., -1.,  3.]])

In [56]:
torch.linalg.det(C_det)

tensor(-26.)

In [57]:
import torch

P = torch.tensor([[25, 2, -5], [3, -2, 1], [5, 7, 4.]])
S = torch.tensor([[25, 2, -5], [2, -2 ,1], [ -5, 1, 4.]])
S, P

(tensor([[25.,  2., -5.],
         [ 2., -2.,  1.],
         [-5.,  1.,  4.]]),
 tensor([[25.,  2., -5.],
         [ 3., -2.,  1.],
         [ 5.,  7.,  4.]]))

In [58]:
P_eigen_values, P_eigen_vectors = torch.linalg.eig(P)
P_eigen_values, P_eigen_vectors

(tensor([23.7644+0.j,  6.6684+0.j, -3.4328+0.j]),
 tensor([[ 0.9511+0.j, -0.2386+0.j,  0.1626+0.j],
         [ 0.1218+0.j, -0.1924+0.j, -0.7705+0.j],
         [ 0.2837+0.j, -0.9519+0.j,  0.6163+0.j]]))

In [59]:
P_eigenval_diag = P_eigen_values.diag()
P_eigenval_diag

tensor([[23.7644+0.j,  0.0000+0.j,  0.0000+0.j],
        [ 0.0000+0.j,  6.6684+0.j,  0.0000+0.j],
        [ 0.0000+0.j,  0.0000+0.j, -3.4328+0.j]])

In [60]:
P_eigen_vectors_inv = torch.linalg.inv(P_eigen_vectors)
P_eigen_vectors_inv

tensor([[ 1.1356+0.j,  0.0102+0.j, -0.2868+0.j],
        [ 0.3914-0.j, -0.7198-0.j, -1.0032-0.j],
        [ 0.0817-0.j, -1.1164-0.j,  0.2052-0.j]])

In [61]:
torch.matmul(P_eigen_vectors, torch.matmul(P_eigenval_diag, P_eigen_vectors_inv))

tensor([[25.0000+0.j,  2.0000+0.j, -5.0000+0.j],
        [ 3.0000+0.j, -2.0000+0.j,  1.0000+0.j],
        [ 5.0000+0.j,  7.0000+0.j,  4.0000+0.j]])

In [62]:
P

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [63]:
S_eigen_values, S_eigen_vectors = torch.linalg.eig(S)
S_eigen_values, S_eigen_vectors

(tensor([26.2361+0.j,  3.2435+0.j, -2.4796+0.j]),
 tensor([[ 0.9744+0.j,  0.1943+0.j, -0.1132+0.j],
         [ 0.0614+0.j,  0.2548+0.j,  0.9651+0.j],
         [-0.2163+0.j,  0.9473+0.j, -0.2363+0.j]]))

In [64]:
torch.matmul(S_eigen_vectors, torch.matmul(S_eigen_values.diag(), S_eigen_vectors.T))

tensor([[25.0000+0.j,  2.0000+0.j, -5.0000+0.j],
        [ 2.0000+0.j, -2.0000+0.j,  1.0000+0.j],
        [-5.0000+0.j,  1.0000+0.j,  4.0000+0.j]])

In [65]:
S

tensor([[25.,  2., -5.],
        [ 2., -2.,  1.],
        [-5.,  1.,  4.]])

In [66]:
import numpy as np

A = np.array([[-1, 2], [3, -2], [5,7]])
A

array([[-1,  2],
       [ 3, -2],
       [ 5,  7]])

In [67]:
U, d, vT = np.linalg.svd(A)
U, d, vT

(array([[ 0.12708324,  0.47409506,  0.87125411],
        [ 0.00164602, -0.87847553,  0.47778451],
        [ 0.99189069, -0.0592843 , -0.11241989]]),
 array([8.66918448, 4.10429538]),
 array([[ 0.55798885,  0.82984845],
        [-0.82984845,  0.55798885]]))

In [68]:
D = np.concatenate((np.diag(d), [[0,0 ]]), axis=0)
D

array([[8.66918448, 0.        ],
       [0.        , 4.10429538],
       [0.        , 0.        ]])

In [69]:
np.dot(U, np.dot(D, vT))

array([[-1.,  2.],
       [ 3., -2.],
       [ 5.,  7.]])

In [70]:
P

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [71]:
U, S_vals, vT = torch.linalg.svd(P)
U, S_vals, vT

(tensor([[-0.9757, -0.1823, -0.1214],
         [-0.0975, -0.1350,  0.9860],
         [-0.1961,  0.9739,  0.1140]]),
 tensor([26.1632,  8.1875,  2.5395]),
 tensor([[-0.9810, -0.1196,  0.1528],
         [-0.0113,  0.8211,  0.5706],
         [ 0.1937, -0.5581,  0.8069]]))

In [72]:
P_PT = P @ P.T
P_PT

tensor([[654.,  66., 119.],
        [ 66.,  14.,   5.],
        [119.,   5.,  90.]])

In [73]:
PPT_eigen_values, PPT_eigen_vectors = torch.linalg.eig(P_PT)
PPT_eigen_values, PPT_eigen_vectors

(tensor([684.5149+0.j,  67.0359+0.j,   6.4492+0.j]),
 tensor([[ 0.9757+0.j,  0.1823+0.j,  0.1214+0.j],
         [ 0.0975+0.j,  0.1350+0.j, -0.9860+0.j],
         [ 0.1961+0.j, -0.9739+0.j, -0.1140+0.j]]))

In [74]:
U

tensor([[-0.9757, -0.1823, -0.1214],
        [-0.0975, -0.1350,  0.9860],
        [-0.1961,  0.9739,  0.1140]])

In [75]:
torch.abs(PPT_eigen_vectors)

tensor([[0.9757, 0.1823, 0.1214],
        [0.0975, 0.1350, 0.9860],
        [0.1961, 0.9739, 0.1140]])

In [76]:
U = U.to(PPT_eigen_vectors.dtype)
U

tensor([[-0.9757+0.j, -0.1823+0.j, -0.1214+0.j],
        [-0.0975+0.j, -0.1350+0.j,  0.9860+0.j],
        [-0.1961+0.j,  0.9739+0.j,  0.1140+0.j]])

In [77]:
torch.allclose(U, PPT_eigen_vectors)

False

In [78]:
P

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [79]:
P_PT = P @ P.T
P_PT

tensor([[654.,  66., 119.],
        [ 66.,  14.,   5.],
        [119.,   5.,  90.]])

In [80]:
P_eigen_values, P_eigen_vectors = torch.linalg.eig(P_PT)
P_eigen_values.to(torch.float32), P_eigen_vectors.to(torch.float32)

C:\Users\archb\AppData\Local\Temp\ipykernel_50676\3957455496.py:2: UserWarning: Casting complex values to real discards the imaginary part (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\Copy.cpp:308.)
  P_eigen_values.to(torch.float32), P_eigen_vectors.to(torch.float32)


(tensor([684.5149,  67.0359,   6.4492]),
 tensor([[ 0.9757,  0.1823,  0.1214],
         [ 0.0975,  0.1350, -0.9860],
         [ 0.1961, -0.9739, -0.1140]]))

In [81]:
U, S_vals, vT = torch.linalg.svd(P)
U, S_vals, vT

(tensor([[-0.9757, -0.1823, -0.1214],
         [-0.0975, -0.1350,  0.9860],
         [-0.1961,  0.9739,  0.1140]]),
 tensor([26.1632,  8.1875,  2.5395]),
 tensor([[-0.9810, -0.1196,  0.1528],
         [-0.0113,  0.8211,  0.5706],
         [ 0.1937, -0.5581,  0.8069]]))

In [82]:
torch.abs(U)

tensor([[0.9757, 0.1823, 0.1214],
        [0.0975, 0.1350, 0.9860],
        [0.1961, 0.9739, 0.1140]])

In [83]:
torch.abs(PPT_eigen_vectors)

tensor([[0.9757, 0.1823, 0.1214],
        [0.0975, 0.1350, 0.9860],
        [0.1961, 0.9739, 0.1140]])

In [84]:
torch.allclose(torch.abs(U), torch.abs(PPT_eigen_vectors))

True

In [85]:
PT_P = P.T @ P
PT_P

tensor([[ 659.,   79., -102.],
        [  79.,   57.,   16.],
        [-102.,   16.,   42.]])

In [86]:
PT_P_eigen_values, PT_P_eigen_vectors = torch.linalg.eig(PT_P)
PT_P_eigen_values.to(torch.float32), PT_P_eigen_vectors.to(torch.float32)  

(tensor([684.5149,   6.4492,  67.0359]),
 tensor([[ 0.9810,  0.1937, -0.0113],
         [ 0.1196, -0.5581,  0.8211],
         [-0.1528,  0.8069,  0.5706]]))

In [87]:
torch.abs(vT)

tensor([[0.9810, 0.1196, 0.1528],
        [0.0113, 0.8211, 0.5706],
        [0.1937, 0.5581, 0.8069]])

In [88]:
torch.allclose(torch.abs(vT), torch.abs(PT_P_eigen_vectors))

False

In [89]:
S_vals

tensor([26.1632,  8.1875,  2.5395])

In [90]:
torch.sqrt(P_eigen_vectors)

tensor([[0.9878+0.0000j, 0.4269+0.0000j, 0.3485+0.0000j],
        [0.3123+0.0000j, 0.3674+0.0000j, 0.0000+0.9930j],
        [0.4429+0.0000j, 0.0000+0.9869j, 0.0000+0.3376j]])

In [91]:
A_p = torch.tensor([[-1, 2], [3, -2], [5,7.]])
A_p

tensor([[-1.,  2.],
        [ 3., -2.],
        [ 5.,  7.]])

In [92]:
torch.pinverse(A_p)

tensor([[-0.0877,  0.1777,  0.0758],
        [ 0.0766, -0.1193,  0.0869]])

In [93]:
U, d, VT = torch.linalg.svd(A_p, full_matrices=False)
U, d, VT

(tensor([[ 0.1271,  0.4741],
         [ 0.0016, -0.8785],
         [ 0.9919, -0.0593]]),
 tensor([8.6692, 4.1043]),
 tensor([[ 0.5580,  0.8298],
         [-0.8298,  0.5580]]))

In [94]:
Dinv = torch.linalg.inv(torch.diag(d))
Dinv

tensor([[0.1154, 0.0000],
        [0.0000, 0.2436]])

In [97]:
sigma_plus = torch.diag(1/ d)
sigma_plus

tensor([[0.1154, 0.0000],
        [0.0000, 0.2436]])

In [102]:
torch.pinverse(A_p)

tensor([[-0.0877,  0.1777,  0.0758],
        [ 0.0766, -0.1193,  0.0869]])

In [103]:
A_p

tensor([[-1.,  2.],
        [ 3., -2.],
        [ 5.,  7.]])

In [104]:
torch.trace(A_p)

tensor(-3.)

In [105]:
torch.linalg.norm(A_p, ord='fro') # Frobenius norm

tensor(9.5917)

In [106]:
torch.linalg.norm(A_p) # Frobenius norm

tensor(9.5917)

In [107]:
torch.sqrt(torch.trace(A_p @ A_p.T))

tensor(9.5917)

In [108]:
import torch

In [109]:
x = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7.])
x

tensor([0., 1., 2., 3., 4., 5., 6., 7.])

In [110]:
m = torch.tensor([0.7]).requires_grad_()
m

tensor([0.7000], requires_grad=True)

In [111]:
b = torch.tensor([0.007]).requires_grad_()
b

tensor([0.0070], requires_grad=True)

In [112]:
y = torch.tensor([1.86, 1.31, .62, .33, .09, -.67, -1.23, -1.37])   
y

tensor([ 1.8600,  1.3100,  0.6200,  0.3300,  0.0900, -0.6700, -1.2300, -1.3700])

In [121]:
def regression(my_x, my_m, my_b):
    return my_x * my_m + my_b

In [122]:
def mse_loss(pred, target):
    sigma = torch.sum((pred - target) ** 2)
    return sigma/ len(target)

In [123]:
cost = mse_loss(regression(x, m, b), y)
cost

tensor(980.0833, grad_fn=<DivBackward0>)

In [124]:
cost.backward()
m.grad, b.grad

(tensor([-260.7042]), tensor([-55.4474]))

In [125]:
optimizer = torch.optim.SGD([m, b], lr=0.01)
optimizer.step()

In [126]:
mse_loss(regression(x, m, b), y)

tensor(399.0400, grad_fn=<DivBackward0>)

In [127]:
epochs = 788 
for epoch in range(epochs):
    cost = mse_loss(regression(x, m, b), y)
    cost.backward()
    optimizer.step()
    optimizer.zero_grad()

    print(f"Epoch {epoch+1}: m={m.item()}, b={b.item()}, cost={cost.item()}")

Epoch 1: m=0.05405092239379883, b=-2.281059741973877, cost=399.0400390625
Epoch 2: m=0.1537572741508484, b=-2.2368721961975098, cost=6.338708877563477
Epoch 3: m=0.21547327935695648, b=-2.200547695159912, cost=5.356086254119873
Epoch 4: m=0.2530459761619568, b=-2.1692698001861572, cost=4.926919937133789
Epoch 5: m=0.275278776884079, b=-2.141247510910034, cost=4.721827983856201
Epoch 6: m=0.28776854276657104, b=-2.115342140197754, cost=4.607670307159424
Epoch 7: m=0.2940734922885895, b=-2.0908291339874268, cost=4.530627250671387
Epoch 8: m=0.2964558005332947, b=-2.0672476291656494, cost=4.468941688537598
Epoch 9: m=0.29635360836982727, b=-2.044304609298706, cost=4.413814544677734
Epoch 10: m=0.2946811616420746, b=-2.021813154220581, cost=4.361685752868652
Epoch 11: m=0.29201966524124146, b=-1.9996545314788818, cost=4.311110973358154
Epoch 12: m=0.2887386083602905, b=-1.9777528047561646, cost=4.261504650115967
Epoch 13: m=0.28507280349731445, b=-1.956059455871582, cost=4.212625026702881


In [128]:
y

tensor([ 1.8600,  1.3100,  0.6200,  0.3300,  0.0900, -0.6700, -1.2300, -1.3700])