In [1]:
import torch
import numpy as np

In [2]:
a = torch.tensor([[2, 5, 1], [8, 9, 11]])
a

tensor([[ 2,  5,  1],
        [ 8,  9, 11]])

In [3]:
b = torch.tensor([[3, 8, 2], [7, 4, 6]])
a

tensor([[ 2,  5,  1],
        [ 8,  9, 11]])

In [4]:
a.T

tensor([[ 2,  8],
        [ 5,  9],
        [ 1, 11]])

In [5]:
torch.matmul(a.T, b)

tensor([[62, 48, 52],
        [78, 76, 64],
        [80, 52, 68]])

In [6]:
torch.matmul(b, a.T)

tensor([[ 48, 118],
        [ 40, 158]])

In [7]:
sym_mt = torch.tensor([[1,2,3], [2,4, 4], [3, 4, 6]])
sym_mt

tensor([[1, 2, 3],
        [2, 4, 4],
        [3, 4, 6]])

In [8]:
sym_mt.T

tensor([[1, 2, 3],
        [2, 4, 4],
        [3, 4, 6]])

In [9]:
sym_mt.T == sym_mt

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [10]:
I = np.array([[1,0,0], [0,1,0], [0,0,1]])
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [11]:
first_column = I[:, 0]
first_column

array([1, 0, 0])

In [12]:
second_column = I[:, 1]
second_column

array([0, 1, 0])

In [13]:
third_column = I[:, 2]
third_column

array([0, 0, 1])

In [14]:
summ = 0
for e in first_column:
    e = e * e
    summ += e
np.square(summ)

np.int64(1)

In [15]:
summ = 0
for e in second_column:
    e = e * e
    summ += e
np.square(summ)

np.int64(1)

In [16]:
summ = 0
for e in third_column:
    e = e * e
    summ += e
np.square(summ)

np.int64(1)

In [17]:
np.linalg.norm(first_column), np.linalg.norm(second_column), np.linalg.norm(third_column)

(np.float64(1.0), np.float64(1.0), np.float64(1.0))

In [18]:
K = np.array([[2/3, 1/3, 2/3], [-2/3, 2/3, 1/3], [1/3, 2/3, -2/3]])
K

array([[ 0.66666667,  0.33333333,  0.66666667],
       [-0.66666667,  0.66666667,  0.33333333],
       [ 0.33333333,  0.66666667, -0.66666667]])

In [19]:
for i in range(3):
    col = K[:, i]
    norm = np.linalg.norm(col)
    print(f"Norm of column {i}: {norm}")

Norm of column 0: 0.9999999999999999
Norm of column 1: 0.9999999999999999
Norm of column 2: 0.9999999999999999


In [20]:
# Orthogonal matrix property check

torch.matmul(torch.tensor(K.T, dtype=torch.float32), torch.tensor(K, dtype=torch.float32))

tensor([[1.0000, 0.0000, 0.0000],
        [0.0000, 1.0000, 0.0000],
        [0.0000, 0.0000, 1.0000]])

In [21]:
u1 = np.array([2,5, -3])
u2 = np.array([0, -4, 6])
u1, u2

(array([ 2,  5, -3]), array([ 0, -4,  6]))

In [22]:
matrix_u = np.concatenate((u1.reshape(3,1), u2.reshape(3,1)), axis=1)
matrix_u

array([[ 2,  0],
       [ 5, -4],
       [-3,  6]])

In [23]:
B = np.array([[2, 0, -1], [-2, 3, 1], [0, 4, -1]])

In [24]:
import torch
B = torch.tensor(B, dtype=torch.float32)
B

tensor([[ 2.,  0., -1.],
        [-2.,  3.,  1.],
        [ 0.,  4., -1.]])

In [25]:
u1 = torch.tensor(u1, dtype=torch.float32)
u1

tensor([ 2.,  5., -3.])

In [26]:
B.matmul(u1)

tensor([ 7.,  8., 23.])

In [27]:
X = torch.tensor([[25, 2, 9], [5,26, -5], [3, 7, -14]], dtype=torch.float32)
X

tensor([[ 25.,   2.,   9.],
        [  5.,  26.,  -5.],
        [  3.,   7., -14.]])

In [42]:
eigen_values, eigen_vectors = torch.linalg.eig(X)
eigen_values.dtype, eigen_vectors.dtype

(torch.complex64, torch.complex64)

In [44]:
X = X.to(eigen_values.dtype)

In [45]:
torch.allclose(X.matmul(eigen_vectors), eigen_vectors.matmul(torch.diag(eigen_values)))

True