In [1]:
import torch
import numpy as np

In [2]:
a = torch.tensor([[2, 5, 1], [8, 9, 11]])
a

tensor([[ 2,  5,  1],
        [ 8,  9, 11]])

In [3]:
b = torch.tensor([[3, 8, 2], [7, 4, 6]])
a

tensor([[ 2,  5,  1],
        [ 8,  9, 11]])

In [4]:
a.T

tensor([[ 2,  8],
        [ 5,  9],
        [ 1, 11]])

In [5]:
torch.matmul(a.T, b)

tensor([[62, 48, 52],
        [78, 76, 64],
        [80, 52, 68]])

In [6]:
torch.matmul(b, a.T)

tensor([[ 48, 118],
        [ 40, 158]])

In [7]:
sym_mt = torch.tensor([[1,2,3], [2,4, 4], [3, 4, 6]])
sym_mt

tensor([[1, 2, 3],
        [2, 4, 4],
        [3, 4, 6]])

In [8]:
sym_mt.T

tensor([[1, 2, 3],
        [2, 4, 4],
        [3, 4, 6]])

In [9]:
sym_mt.T == sym_mt

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [10]:
I = np.array([[1,0,0], [0,1,0], [0,0,1]])
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [11]:
first_column = I[:, 0]
first_column

array([1, 0, 0])

In [12]:
second_column = I[:, 1]
second_column

array([0, 1, 0])

In [13]:
third_column = I[:, 2]
third_column

array([0, 0, 1])

In [14]:
summ = 0
for e in first_column:
    e = e * e
    summ += e
np.square(summ)

np.int64(1)

In [15]:
summ = 0
for e in second_column:
    e = e * e
    summ += e
np.square(summ)

np.int64(1)

In [16]:
summ = 0
for e in third_column:
    e = e * e
    summ += e
np.square(summ)

np.int64(1)

In [17]:
np.linalg.norm(first_column), np.linalg.norm(second_column), np.linalg.norm(third_column)

(np.float64(1.0), np.float64(1.0), np.float64(1.0))

In [18]:
K = np.array([[2/3, 1/3, 2/3], [-2/3, 2/3, 1/3], [1/3, 2/3, -2/3]])
K

array([[ 0.66666667,  0.33333333,  0.66666667],
       [-0.66666667,  0.66666667,  0.33333333],
       [ 0.33333333,  0.66666667, -0.66666667]])

In [19]:
for i in range(3):
    col = K[:, i]
    norm = np.linalg.norm(col)
    print(f"Norm of column {i}: {norm}")

Norm of column 0: 0.9999999999999999
Norm of column 1: 0.9999999999999999
Norm of column 2: 0.9999999999999999


In [20]:
# Orthogonal matrix property check

torch.matmul(torch.tensor(K.T, dtype=torch.float32), torch.tensor(K, dtype=torch.float32))

tensor([[1.0000, 0.0000, 0.0000],
        [0.0000, 1.0000, 0.0000],
        [0.0000, 0.0000, 1.0000]])

In [21]:
u1 = np.array([2,5, -3])
u2 = np.array([0, -4, 6])
u1, u2

(array([ 2,  5, -3]), array([ 0, -4,  6]))

In [22]:
matrix_u = np.concatenate((u1.reshape(3,1), u2.reshape(3,1)), axis=1)
matrix_u

array([[ 2,  0],
       [ 5, -4],
       [-3,  6]])

In [23]:
B = np.array([[2, 0, -1], [-2, 3, 1], [0, 4, -1]])

In [24]:
import torch
B = torch.tensor(B, dtype=torch.float32)
B

tensor([[ 2.,  0., -1.],
        [-2.,  3.,  1.],
        [ 0.,  4., -1.]])

In [25]:
u1 = torch.tensor(u1, dtype=torch.float32)
u1

tensor([ 2.,  5., -3.])

In [26]:
B.matmul(u1)

tensor([ 7.,  8., 23.])

In [27]:
X = torch.tensor([[25, 2, 9], [5,26, -5], [3, 7, -14]], dtype=torch.float32)
X

tensor([[ 25.,   2.,   9.],
        [  5.,  26.,  -5.],
        [  3.,   7., -14.]])

In [42]:
eigen_values, eigen_vectors = torch.linalg.eig(X)
eigen_values.dtype, eigen_vectors.dtype

(torch.complex64, torch.complex64)

In [44]:
X = X.to(eigen_values.dtype)

In [45]:
torch.allclose(X.matmul(eigen_vectors), eigen_vectors.matmul(torch.diag(eigen_values)))

True

In [ ]:
A = torch.tensor([[-1, 4], [2, -2.]])
A

tensor([[-1.,  4.],
        [ 2., -2.]])

In [56]:
eig_v, eig_vec = torch.linalg.eig(A)
eig_v, eig_vec

(tensor([ 1.3723+0.j, -4.3723+0.j]),
 tensor([[ 0.8601+0.j, -0.7645+0.j],
         [ 0.5101+0.j,  0.6446+0.j]]))

In [60]:
A = A.to(eig_v.dtype)
A

tensor([[-1.+0.j,  4.+0.j],
        [ 2.+0.j, -2.+0.j]])

In [61]:
vec1 = eig_vec[:, 0]
val1 = eig_v[0]
vec1, val1

(tensor([0.8601+0.j, 0.5101+0.j]), tensor(1.3723+0.j))

In [62]:
Av_p = A.matmul(vec1)
Av_p

tensor([1.1803+0.j, 0.7000+0.j])

In [63]:
vec1 * val1

tensor([1.1803+0.j, 0.7000+0.j])

In [65]:
val2 = eig_v[1]
vec2 = eig_vec[:, 1]
val2, vec2

(tensor(-4.3723+0.j), tensor([-0.7645+0.j,  0.6446+0.j]))

In [66]:
Av2_P = A.matmul(vec2)
Av2_P

tensor([ 3.3428+0.j, -2.8182+0.j])

In [67]:
val2 * vec2

tensor([ 3.3428-0.j, -2.8182+0.j])

In [68]:
X = torch.tensor([[25, 2, 9], [5, 26, -5], [3, 7, -14.]])
X

tensor([[ 25.,   2.,   9.],
        [  5.,  26.,  -5.],
        [  3.,   7., -14.]])

In [69]:
eig_val, eig_vec = torch.linalg.eig(X)
eig_val, eig_vec

(tensor([ 29.4214+0.j,  21.2058+0.j, -13.6271+0.j]),
 tensor([[ 0.6633+0.j,  0.6360+0.j, -0.2317+0.j],
         [ 0.7303+0.j, -0.7655+0.j,  0.1505+0.j],
         [ 0.1636+0.j, -0.0980+0.j,  0.9611+0.j]]))

In [73]:
X = X.to(eig_vec.dtype)
X

tensor([[ 25.+0.j,   2.+0.j,   9.+0.j],
        [  5.+0.j,  26.+0.j,  -5.+0.j],
        [  3.+0.j,   7.+0.j, -14.+0.j]])

In [72]:
eig_vec1 = eig_vec[:, 0]
eig_val1 = eig_val[0]
eig_vec1, eig_val1

(tensor([0.6633+0.j, 0.7303+0.j, 0.1636+0.j]), tensor(29.4214+0.j))

In [76]:
X.matmul(eig_vec1)

tensor([19.5144+0.j, 21.4861+0.j,  4.8120+0.j])

In [77]:
eig_val1 * eig_vec1

tensor([19.5144+0.j, 21.4861+0.j,  4.8120+0.j])

In [75]:
torch.allclose(X.matmul(eig_vec1), eig_val1 * eig_vec1)

True

In [78]:
eig_vec2 = eig_vec[:, 1]
eig_val2 = eig_val[1]
eig_vec2, eig_val2

(tensor([ 0.6360+0.j, -0.7655+0.j, -0.0980+0.j]), tensor(21.2058+0.j))

In [79]:
X.matmul(eig_vec2)

tensor([ 13.4861+0.j, -16.2324+0.j,  -2.0783+0.j])

In [80]:
eig_val2 * eig_vec2

tensor([ 13.4861+0.j, -16.2324+0.j,  -2.0783+0.j])

In [81]:
eig_vec3 = eig_vec[:, 2]
eig_val3 = eig_val[2]
eig_vec3, eig_val3

(tensor([-0.2317+0.j,  0.1505+0.j,  0.9611+0.j]), tensor(-13.6271+0.j))

In [82]:
X.matmul(eig_vec3)

tensor([  3.1577+0.j,  -2.0509+0.j, -13.0966+0.j])

In [83]:
eig_val3 * eig_vec3

tensor([  3.1577-0.j,  -2.0509+0.j, -13.0966+0.j])

In [86]:
B_det = torch.tensor([[-2, 0], [0, -2.]])
B_det

tensor([[-2.,  0.],
        [ 0., -2.]])

In [87]:
torch.linalg.det(B_det)

tensor(4.)

In [90]:
C_det = torch.tensor([[2,1,-3], [4,-5,2], [0,-1,3.]])
C_det

tensor([[ 2.,  1., -3.],
        [ 4., -5.,  2.],
        [ 0., -1.,  3.]])

In [91]:
torch.linalg.det(C_det)

tensor(-26.)

In [1]:
import torch

P = torch.tensor([[25, 2, -5], [3, -2, 1], [5, 7, 4.]])
S = torch.tensor([[25, 2, -5], [2, -2 ,1], [ -5, 1, 4.]])
S, P

(tensor([[25.,  2., -5.],
         [ 2., -2.,  1.],
         [-5.,  1.,  4.]]),
 tensor([[25.,  2., -5.],
         [ 3., -2.,  1.],
         [ 5.,  7.,  4.]]))

In [2]:
P_eigen_values, P_eigen_vectors = torch.linalg.eig(P)
P_eigen_values, P_eigen_vectors

(tensor([23.7644+0.j,  6.6684+0.j, -3.4328+0.j]),
 tensor([[ 0.9511+0.j, -0.2386+0.j,  0.1626+0.j],
         [ 0.1218+0.j, -0.1924+0.j, -0.7705+0.j],
         [ 0.2837+0.j, -0.9519+0.j,  0.6163+0.j]]))

In [6]:
P_eigenval_diag = P_eigen_values.diag()
P_eigenval_diag

tensor([[23.7644+0.j,  0.0000+0.j,  0.0000+0.j],
        [ 0.0000+0.j,  6.6684+0.j,  0.0000+0.j],
        [ 0.0000+0.j,  0.0000+0.j, -3.4328+0.j]])

In [7]:
P_eigen_vectors_inv = torch.linalg.inv(P_eigen_vectors)
P_eigen_vectors_inv

tensor([[ 1.1356+0.j,  0.0102+0.j, -0.2868+0.j],
        [ 0.3914-0.j, -0.7198-0.j, -1.0032-0.j],
        [ 0.0817-0.j, -1.1164-0.j,  0.2052-0.j]])

In [8]:
torch.matmul(P_eigen_vectors, torch.matmul(P_eigenval_diag, P_eigen_vectors_inv))

tensor([[25.0000+0.j,  2.0000+0.j, -5.0000+0.j],
        [ 3.0000+0.j, -2.0000+0.j,  1.0000+0.j],
        [ 5.0000+0.j,  7.0000+0.j,  4.0000+0.j]])

In [9]:
P

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [10]:
S_eigen_values, S_eigen_vectors = torch.linalg.eig(S)
S_eigen_values, S_eigen_vectors

(tensor([26.2361+0.j,  3.2435+0.j, -2.4796+0.j]),
 tensor([[ 0.9744+0.j,  0.1943+0.j, -0.1132+0.j],
         [ 0.0614+0.j,  0.2548+0.j,  0.9651+0.j],
         [-0.2163+0.j,  0.9473+0.j, -0.2363+0.j]]))

In [11]:
torch.matmul(S_eigen_vectors, torch.matmul(S_eigen_values.diag(), S_eigen_vectors.T))

tensor([[25.0000+0.j,  2.0000+0.j, -5.0000+0.j],
        [ 2.0000+0.j, -2.0000+0.j,  1.0000+0.j],
        [-5.0000+0.j,  1.0000+0.j,  4.0000+0.j]])

In [12]:
S

tensor([[25.,  2., -5.],
        [ 2., -2.,  1.],
        [-5.,  1.,  4.]])

In [13]:
import numpy as np

A = np.array([[-1, 2], [3, -2], [5,7]])
A

array([[-1,  2],
       [ 3, -2],
       [ 5,  7]])

In [14]:
U, d, vT = np.linalg.svd(A)
U, d, vT

(array([[ 0.12708324,  0.47409506,  0.87125411],
        [ 0.00164602, -0.87847553,  0.47778451],
        [ 0.99189069, -0.0592843 , -0.11241989]]),
 array([8.66918448, 4.10429538]),
 array([[ 0.55798885,  0.82984845],
        [-0.82984845,  0.55798885]]))

In [21]:
D = np.concatenate((np.diag(d), [[0,0 ]]), axis=0)
D

array([[8.66918448, 0.        ],
       [0.        , 4.10429538],
       [0.        , 0.        ]])

In [22]:
np.dot(U, np.dot(D, vT))

array([[-1.,  2.],
       [ 3., -2.],
       [ 5.,  7.]])