In [13]:
import torch
import numpy as np

In [10]:
a = torch.tensor([[2, 5, 1], [8, 9, 11]])
a

tensor([[ 2,  5,  1],
        [ 8,  9, 11]])

In [11]:
b = torch.tensor([[3, 8, 2], [7, 4, 6]])
a

tensor([[ 2,  5,  1],
        [ 8,  9, 11]])

In [12]:
a.T

tensor([[ 2,  8],
        [ 5,  9],
        [ 1, 11]])

In [7]:
torch.matmul(a.T, b)

tensor([[62, 48, 52],
        [78, 76, 64],
        [80, 52, 68]])

In [9]:
torch.matmul(b, a.T)

tensor([[ 48, 118],
        [ 40, 158]])

In [17]:
sym_mt = torch.tensor([[1,2,3], [2,4, 4], [3, 4, 6]])
sym_mt

tensor([[1, 2, 3],
        [2, 4, 4],
        [3, 4, 6]])

In [18]:
sym_mt.T

tensor([[1, 2, 3],
        [2, 4, 4],
        [3, 4, 6]])

In [19]:
sym_mt.T == sym_mt

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])