In [1]:
import torch
import numpy as np

In [10]:
a = torch.tensor([[2, 5, 1], [8, 9, 11]])
a

tensor([[ 2,  5,  1],
        [ 8,  9, 11]])

In [11]:
b = torch.tensor([[3, 8, 2], [7, 4, 6]])
a

tensor([[ 2,  5,  1],
        [ 8,  9, 11]])

In [12]:
a.T

tensor([[ 2,  8],
        [ 5,  9],
        [ 1, 11]])

In [7]:
torch.matmul(a.T, b)

tensor([[62, 48, 52],
        [78, 76, 64],
        [80, 52, 68]])

In [9]:
torch.matmul(b, a.T)

tensor([[ 48, 118],
        [ 40, 158]])

In [17]:
sym_mt = torch.tensor([[1,2,3], [2,4, 4], [3, 4, 6]])
sym_mt

tensor([[1, 2, 3],
        [2, 4, 4],
        [3, 4, 6]])

In [18]:
sym_mt.T

tensor([[1, 2, 3],
        [2, 4, 4],
        [3, 4, 6]])

In [19]:
sym_mt.T == sym_mt

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [3]:
I = np.array([[1,0,0], [0,1,0], [0,0,1]])
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [9]:
first_column = I[:, 0]
first_column

array([1, 0, 0])

In [5]:
second_column = I[:, 1]
second_column

array([0, 1, 0])

In [7]:
third_column = I[:, 2]
third_column

array([0, 0, 1])

In [13]:
summ = 0
for e in first_column:
    e = e * e
    summ += e
np.square(summ)

np.int64(1)

In [15]:
summ = 0
for e in second_column:
    e = e * e
    summ += e
np.square(summ)

np.int64(1)

In [16]:
summ = 0
for e in third_column:
    e = e * e
    summ += e
np.square(summ)

np.int64(1)

In [17]:
np.linalg.norm(first_column), np.linalg.norm(second_column), np.linalg.norm(third_column)

(np.float64(1.0), np.float64(1.0), np.float64(1.0))

In [18]:
K = np.array([[2/3, 1/3, 2/3], [-2/3, 2/3, 1/3], [1/3, 2/3, -2/3]])
K

array([[ 0.66666667,  0.33333333,  0.66666667],
       [-0.66666667,  0.66666667,  0.33333333],
       [ 0.33333333,  0.66666667, -0.66666667]])

In [19]:
for i in range(3):
    col = K[:, i]
    norm = np.linalg.norm(col)
    print(f"Norm of column {i}: {norm}")

Norm of column 0: 0.9999999999999999
Norm of column 1: 0.9999999999999999
Norm of column 2: 0.9999999999999999


In [21]:
# Orthogonal matrix property check

torch.matmul(torch.tensor(K.T, dtype=torch.float32), torch.tensor(K, dtype=torch.float32))

tensor([[1.0000, 0.0000, 0.0000],
        [0.0000, 1.0000, 0.0000],
        [0.0000, 0.0000, 1.0000]])